server:
port: 9091

encrypt:
    key: "mitocode-secret"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka} #http://localhost:8761/eureka 